ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "firstName" TEXT;
ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "lastName" TEXT;
ALTER TABLE "Entry" ADD COLUMN IF NOT EXISTS "honorific" TEXT;
ALTER TYPE "EntryType" ADD VALUE IF NOT EXISTS 'ARTICLE';
